### ISSUE TITLE
Downcase in canonical_url causes problem

### ISSUE THREAD

**Issue by maiertech** [octopress/filters#2]
This is a little bit of a corner case. I noticed in the feeds templates that `canonical_url` downcases the entire URL. There are cases when parts of the URL should not be downcased.

Example: I'm using GitHub pages to publish a test site. Unfortunately, the repo name is UNStats-theme with some capitals. This means that the gh-pages URL for repo UNStats/UNStats-theme is

```
http://unstats.github.io/UNStats-theme/
```

Notice the lower case in the subdomain, i.e. gh-pages ignores uppercases in the organization name/user name. But: GitHub pages honors the capitalization of the repo name, i.e. `http://unstats.github.io/unstats-theme` throws a 404.

In this case downcasing the entire URL in `canonical_url` breaks the URL.

**Comment by imathis** [comment]
Hmm. That's really frustrating. I suppose I should change this since I don't know how people will intentionally or unintentionally face this issue. Uppercase characters in urls are really a pain for users. If I were you, I'd downcase the name of the repo regardless. I get why you'd rather not do that, but if you're going to depend on this URL for anything, enforcing capital letters is terrible for the web.

**Comment by maiertech** [comment]
I agree re uppercase chars in URLs. This issue should probably be fixed on the GitHub Pages platform by lower-casing there. In any case, as you said, it seems to be better to avoid capitals in repo names in the first place.
